openapi: 3.0.0
info:
  title: Webhooks
  version: '1.0'
  contact:
    name: ReCharge
    url: rechargepayments.com
  termsOfService: 'https://rechargepayments.com/terms-of-service/'
  description: Use webhooks to listen for events within the ReCharge app.
servers:
  - url: 'https://api.rechargeapps.com/webhooks'
paths:
  '/webhooks/{id}':
    get:
      summary: Retrieve Webhook
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-webhooks
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              $ref: ../models/webhook.v1.yaml
    parameters: []
    post:
      summary: Create Webhook
      operationId: post-webhooks-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webhook-response'
components:
  schemas: {}
  securitySchemes: {}
