openapi: 3.0.0
info:
  title: Webhooks
  version: '1.0'
  contact:
    name: ReCharge
    url: rechargepayments.com
  termsOfService: 'https://rechargepayments.com/terms-of-service/'
  description: Use webhooks to listen for events within the ReCharge app.
servers:
  - url: 'https://api.rechargeapps.com/webhooks'
paths:
  '/webhooks/{id}':
    get:
      summary: Retrieve Webhook
      tags: []
      operationId: get-webhooks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  webhook:
                    $ref: ../models/webhook-response.v1.yaml
              examples:
                Example:
                  value:
                    webhook:
                      address: 'https://request.in/foo'
                      id: 19451
                      topic: subscription/created
      description: Retrieve a webhook by ID.
    parameters: []
    post:
      summary: Create Webhook
      operationId: post-webhooks-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/webhook-response'
components:
  schemas: {}
  securitySchemes: {}
